<script src="<?php echo base_url() ?>asset/mitra/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/plugins.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/main.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/lib/chart-js/Chart.bundle.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/dashboard.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/widgets.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/lib/vector-map/jquery.vmap.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/lib/vector-map/jquery.vmap.min.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
    <script src="<?php echo base_url() ?>asset/mitra/assets/js/lib/vector-map/country/jquery.vmap.world.js"></script>